start script for ruby needs a Procfile

diff --git a/precise/ruby/hooks/start b/precise/ruby/hooks/start
--- a/precise/ruby/hooks/start
+++ b/precise/ruby/hooks/start
@@ -4,3 +4,13 @@ APP_DIR=/home/application
 CURRENT_DIR=${APP_DIR}/current
 
 cd $CURRENT_DIR
+
+if [ -f [ Procfile ]; then
+    `cat Procfile |cut -d: -f2` >> $APP_DIR/ruby-server.log 2>&1 &
+    echo $! > $APP_DIR/ruby-server.pid
+else
+    echo "${CURRENT_DIR}/Procfile not found"
+    exit 1
+fi
+
+cd -
