centos/gunicorn: changed start-gunicorn to check presence of wsgi.py

diff --git a/centos/gunicorn/hooks/start-gunicorn b/centos/gunicorn/hooks/start-gunicorn
--- a/centos/gunicorn/hooks/start-gunicorn
+++ b/centos/gunicorn/hooks/start-gunicorn
@@ -11,7 +11,13 @@ then
     ENV_FILE=${APP_DIR}/apprc
     [ -f ${ENV_FILE} ] && source ${ENV_FILE}
     cd $APP_DIR/current/
-    gunicorn --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid wsgi:app --access-logfile=${APP_DIR}/gunicorn_access.log --error-logfile=${APP_DIR}/gunicorn_error.log
+    if [ -f wsgi.py ]
+    then
+        gunicorn --daemon --workers=${NUM_WORKERS} --bind=127.0.0.1:8888 --pid=${APP_DIR}/gunicorn.pid wsgi:app --access-logfile=${APP_DIR}/gunicorn_access.log --error-logfile=${APP_DIR}/gunicorn_error.log
+    else
+        echo "ERROR: failed to start gunicorn. wsgi.py must be located at the app root directory"
+        exit 1
+    fi
     cd $OLDPWD
 else
     juju-log "skipping gunicorn start: app not deployed yet"
